
import React from 'react';
import {
  MessageSquare, Calculator, Speech, History, Globe, Atom, Beaker, Leaf, BookOpen, School, DollarSign, Laptop, Palette, Music, Volleyball, Scale, Book
} from 'lucide-react';
import { Timestamp } from '@firebase/firestore';
import type { AppUser } from './types';

export const allSubjects: string[] = [
  "nederlands", "wiskunde", "engels", "geschiedenis", "aardrijkskunde",
  "natuurkunde", "scheikunde", "biologie", "frans", "duits", "economie",
  "informatica", "kunst", "muziek", "lichamelijke_opvoeding",
  "maatschappijleer", "ckv", "algemeen"
];

export const subjectIconMap: { [key: string]: React.ElementType } = {
  "nederlands": MessageSquare,
  "wiskunde": Calculator,
  "engels": Speech,
  "geschiedenis": History,
  "aardrijkskunde": Globe,
  "natuurkunde": Atom,
  "scheikunde": Beaker,
  "biologie": Leaf,
  "frans": BookOpen,
  "duits": School,
  "economie": DollarSign,
  "informatica": Laptop,
  "kunst": Palette,
  "muziek": Music,
  "lichamelijke_opvoeding": Volleyball,
  "maatschappijleer": Scale,
  "ckv": Palette, // CKV is culturele en KUNSTzinnige vorming
  "algemeen": Book,
  "default": Book
};

export const subjectDisplayTranslations: { [key: string]: { [key: string]: string } } = {
  nl: {
    "nederlands": "Nederlands", "wiskunde": "Wiskunde", "engels": "Engels", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "natuurkunde": "Natuurkunde", "scheikunde": "Scheikunde", "biologie": "Biologie", "frans": "Frans", "duits": "Duits", "economie": "Economie",
    "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek", "lichamelijke_opvoeding": "Lichamelijke Opvoeding",
    "maatschappijleer": "Maatschappijleer", "ckv": "CKV", "algemeen": "Algemeen",
  },
  en: {
    "nederlands": "Dutch", "wiskunde": "Mathematics", "engels": "English", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "natuurkunde": "Physics", "scheikunde": "Chemistry", "biologie": "Biology", "frans": "French", "duits": "German", "economie": "Economics",
    "informatica": "Computer Science", "kunst": "Art", "muziek": "Music", "lichamelijke_opvoeding": "Physical Education",
    "maatschappijleer": "Social Studies", "ckv": "CAE", "algemeen": "General",
  }
};

export const educationLevels: string[] = ["vmbo", "havo", "vwo"];

export const defaultProfileImage: string = "https://picsum.photos/100/100";

export const availableThemeColors: string[] = ['emerald', 'blue', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const translations: { [key: string]: { [key: string]: string } } = {
  nl: {
    // Auth & General
    welcome_title: "Welkom bij Schoolmaps!",
    welcome_description: "Al je schoolzaken op één plek. Organiseer je bestanden, beheer je agenda en versnel je leerproces.",
    create_account_login_button: "Account Aanmaken / Inloggen",
    register_title: "Registreer een Account",
    login_title: "Inloggen",
    your_name: "Volledige naam",
    email_address: "E-mailadres",
    password: "Wachtwoord",
    placeholder_name: "bv. Jan Jansen",
    placeholder_email: "jouw@email.com",
    placeholder_password: "********",
    school_name: "Naam van je school",
    class_name: "Klas (bv. H4B)",
    education_level: "Onderwijsniveau",
    register_account: "Registreer Account",
    login_button: "Login",
    already_account: "Al een account? Login hier",
    no_account_register: "Nog geen account? Registreer hier",
    success_registration: "Registratie succesvol! Welkom bij Schoolmaps!",
    success_login: "Succesvol ingelogd! Welkom terug.",
    success_logout: "Je bent uitgelogd. Tot de volgende keer!",
    confirm_logout: "Weet je zeker dat je wilt uitloggen?",
    forgot_password: "Wachtwoord vergeten?",
    password_reset_sent: "Een e-mail voor wachtwoordherstel is verzonden naar {email}.",
    guest_fallback_name: "Gebruiker",
    
    // Errors
    error_fill_all_fields: "Vul alstublieft alle verplichte velden in.",
    error_unknown: "Er is een onbekende fout opgetreden. Probeer het opnieuw.",
    error_invalid_email: "Dit is geen geldig e-mailadres. Controleer het en probeer opnieuw.",
    error_invalid_credentials: "De combinatie van e-mail en wachtwoord is onjuist.",
    error_email_in_use: "Dit e-mailadres is al in gebruik. Probeer in te loggen.",
    error_weak_password: "Je wachtwoord is te zwak. Gebruik minimaal 6 tekens.",
    error_enter_email_for_reset: "Voer je e-mailadres in om je wachtwoord te resetten.",
    error_save_settings_failed: "Opslaan van instellingen mislukt. Probeer het opnieuw.",
    error_profile_pic_upload_failed: "Uploaden van profielfoto mislukt. Probeer het opnieuw.",
    error_password_reset_failed: "Verzenden van wachtwoordherstel mislukt.",
    error_guest_action_not_allowed: "Gastgebruikers kunnen deze actie niet uitvoeren.",
    error_profile_load_failed: "Kon je profiel niet laden. Controleer je verbinding of probeer het later opnieuw.",

    // Navigation
    my_subjects: "Mijn Vakken",
    calendar: "Agenda",
    extra_tools: "Extra Tools",
    flashcards: "Flashcards",
    study_timer: "Studeertimer",
    notes: "Notities",
    todo_list: "Takenlijst",
    settings: "Instellingen",
    app_info: "App Info",
    faq: "Veelgestelde Vragen",
    logout_button: "Uitloggen",
    
    // Home & Subjects
    my_subjects_files: "Jouw School Bestanden",
    profile_incomplete_message: "Je profiel is nog niet compleet!",
    go_to_settings_message: "Ga naar Instellingen om je vakken te selecteren.",
    select_subjects: "Selecteer je vakken",
    no_files_found: "Geen bestanden gevonden in dit vak.",
    add_file_section_title: "Bestand toevoegen:",
    file_title_placeholder: "Titel (verplicht)",
    file_description_placeholder: "Beschrijving (optioneel)",
    add_file_button: "Voeg Bestand Toe",
    select_files_button: "Selecteer Bestanden",
    delete_selected_button: "Verwijder Geselecteerde",
    share_button: "Deel",
    back_to_subjects: "Terug naar Vakken",
    back_button: "Terug",
    error_enter_file_title: "Voer een titel in voor het bestand.",
    success_file_added: "Bestand succesvol toegevoegd!",
    error_select_files_delete: "Selecteer eerst bestanden om te verwijderen.",
    confirm_delete_files: "Weet je zeker dat je {count} bestand(en) wilt verwijderen?",
    success_files_deleted: "Geselecteerde bestanden succesvol verwijderd!",
    share_link_copied: "Deellink voor '{title}' gekopieerd!",
    error_copy_share_link: "Fout bij kopiëren deellink.",
    added_on: "Toegevoegd op",
    your_files_in: "Jouw bestanden in",
    your_subjects: "Jouw Vakken",
    recent_files_title: "Recente Bestanden",
    no_recent_files: "Je hebt nog geen bestanden toegevoegd.",

    // Settings
    settings_title: "Instellingen",
    profile_section: "Profiel",
    profile_picture_upload_label: "Profielfoto uploaden:",
    profile_picture_current: "Huidige profielfoto:",
    profile_picture_upload_success: "Profielfoto succesvol bijgewerkt!",
    upload_profile_picture_button: "Upload Profielfoto",
    save_profile_info_button: "Profiel Opslaan",
    success_settings_saved: "Instellingen succesvol opgeslagen!",
    choose_theme: "Kies je thema",
    language_preference: "Taalvoorkeur",
    dutch: "Nederlands",
    english: "Engels",
    password_reset_section_title: "Wachtwoord Resetten",
    password_reset_section_description: "Klik op de knop om een wachtwoordherstele-mail te ontvangen op {email}.",
    send_reset_email_button: "Verstuur Herstel E-mail",
    settings_account_section: "Account",
    settings_appearance_section: "Weergave",
    settings_help_info_section: "Hulp & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Uw privacy is belangrijk voor ons. Deze app verzamelt minimale persoonlijke gegevens om de functionaliteit te bieden. Bestanden die u uploadt, worden in uw privéopslag opgeslagen en zijn alleen voor u toegankelijk, tenzij u ze expliciet deelt.",
    version: "Versie",
    copyright: "Alle rechten voorbehouden.",
    saving: "Opslaan...",
    confirm_remove_subjects_warning: "Weet je zeker dat je deze vakken wilt deselecteren? De bijbehorende gegevens (bestanden, notities, etc.) worden niet verwijderd, maar zijn pas weer zichtbaar als je de vakken opnieuw selecteert.",
    app_offline_message: "U bent offline. Wijzigingen worden gesynchroniseerd wanneer u weer online bent.",
    app_back_online_message: "Welkom terug online! Uw gegevens worden gesynchroniseerd.",
    
    // Calendar
    calendar_title: "Jouw Agenda",
    add_event: "Nieuwe Afspraak",
    event_title: "Titel afspraak",
    event_description: "Beschrijving (optioneel)",
    event_type: "Type",
    event_subject: "Vak",
    select_date: "Datum",
    select_start_time: "Starttijd",
    select_end_time: "Eindtijd",
    add_event_button: "Voeg afspraak toe",
    no_events_day: "Geen afspraken voor deze dag.",
    edit_event: "Bewerken",
    delete_event_confirm: "Weet je zeker dat je '{title}' wilt verwijderen?",
    event_test: "Toets",
    event_presentation: "Presentatie",
    event_homework: "Huiswerk",
    event_oral: "Mondeling",
    event_other: "Overig",
    all_day: "Hele dag",
    today: "Vandaag",
    week_of: "Week van",
    previous_week: "Vorige",
    next_week: "Volgende",
    error_enter_event_title: "Voer een titel in voor de afspraak.",
    success_event_added: "Afspraak succesvol toegevoegd!",
    success_event_updated: "Afspraak succesvol bijgewerkt!",
    success_event_deleted: "Afspraak succesvol verwijderd!",
    all_subjects_option: "Alle Vakken",

    // Tools
    notes_title: "Notities",
    add_note_title_placeholder: "Titel notitie (verplicht)",
    add_note_content_placeholder: "Begin met typen...",
    add_note_button: "Nieuwe Notitie",
    save_note_button: "Opslaan",
    confirm_delete_note: "Weet je zeker dat je deze notitie wilt verwijderen?",
    note_added_success: "Notitie succesvol toegevoegd!",
    note_updated_success: "Notitie succesvol bijgewerkt!",
    note_deleted_success: "Notitie succesvol verwijderd!",
    error_empty_note_title: "Titel van notitie mag niet leeg zijn.",
    
    todo_list_title: "Jouw Takenlijst",
    add_task_placeholder: "Voeg een nieuwe taak toe...",
    add_task_button: "Taak Toevoegen",
    no_tasks_found: "Geen taken gevonden. Voeg er een toe!",
    task_added_success: "Taak succesvol toegevoegd!",
    task_deleted_success: "Taak succesvol verwijderd!",
    task_updated_success: "Taak succesvol bijgewerkt!",
    confirm_delete_task: "Weet je zeker dat je deze taak wilt verwijderen?",
    error_empty_task: "Taak mag niet leeg zijn.",

    flashcards_title: "Jouw Flashcards",
    add_flashcard: "Flashcard Toevoegen",
    question: "Vraag",
    answer: "Antwoord",
    add_card_button: "Kaart Toevoegen",
    next_card: "Volgende",
    prev_card: "Vorige",
    flip_card: "Omdraaien",
    no_flashcards_found: "Geen flashcards gevonden voor dit deck.",
    confirm_delete_flashcard: "Weet je zeker dat je deze flashcard wilt verwijderen?",
    flashcard_added_success: "Flashcards succesvol toegevoegd!",
    flashcard_deleted_success: "Flashcard succesvol verwijderd!",
    error_empty_flashcard: "Vraag en antwoord mogen niet leeg zijn.",
    
    // New Flashcard Deck translations
    select_a_subject_first: "Selecteer een vak om te beginnen",
    decks_for_subject: "Decks voor {subject}",
    select_deck: "Selecteer een Deck",
    create_new_deck: "Nieuw Deck Maken",
    deck_name_placeholder: "Naam van je deck (bv. Hoofdstuk 1)",
    create_deck_button: "Maak Deck",
    no_decks_found: "Geen decks gevonden voor dit vak.",
    confirm_delete_deck: "Weet je zeker dat je het deck '{name}' en alle kaarten erin wilt verwijderen?",
    deck_added_success: "Deck succesvol aangemaakt!",
    deck_deleted_success: "Deck succesvol verwijderd!",
    error_empty_deck_name: "Decknaam mag niet leeg zijn.",
    back_to_decks: "Terug naar Decks",
    back_to_subjects_selection: "Terug naar vakken",
    study_deck: "Bestudeer dit Deck",
    cards_in_deck: "{count} kaarten",
    session_complete: "Sessie voltooid!",
    restart_session: "Opnieuw Beginnen",
    cards_to_go: "{count} kaarten te gaan",
    add_more_rows: "Voeg 5 extra rijen toe",

    study_timer_title: "Studeertimer",
    focus_session: "Focus",
    break_session: "Pauze",
    
    // UI
    confirm_button: "Bevestigen",
    cancel_button: "Annuleren",
    close_button: "Sluiten",
    Selecteer_Niveau: "Selecteer Niveau",
    Bekijk: "Bekijk",
    Verwijder: "Verwijder",
    copy_link: "Kopieer Link",
  },
  en: {
    welcome_title: "Welcome to Schoolmaps!",
    welcome_description: "All your school matters in one place. Organize files, manage your calendar, and speed up your learning.",
    create_account_login_button: "Create Account / Login",
    register_title: "Register an Account",
    login_title: "Login",
    your_name: "Full Name",
    email_address: "Email Address",
    password: "Password",
    placeholder_name: "e.g. John Doe",
    placeholder_email: "your@email.com",
    placeholder_password: "********",
    school_name: "School Name",
    class_name: "Class (e.g. 10B)",
    education_level: "Education Level",
    register_account: "Register Account",
    login_button: "Login",
    already_account: "Already have an account? Login here",
    no_account_register: "No account yet? Register here",
    success_registration: "Registration successful! Welcome to Schoolmaps!",
    success_login: "Successfully logged in! Welcome back.",
    success_logout: "You have been logged out. See you next time!",
    confirm_logout: "Are you sure you want to log out?",
    forgot_password: "Forgot Password?",
    password_reset_sent: "A password reset email has been sent to {email}.",
    guest_fallback_name: "User",
    error_fill_all_fields: "Please fill in all required fields.",
    error_unknown: "An unknown error occurred. Please try again.",
    error_invalid_email: "This is not a valid email address. Please check and try again.",
    error_invalid_credentials: "The email and password combination is incorrect.",
    error_email_in_use: "This email address is already in use. Try logging in.",
    error_weak_password: "Your password is too weak. Please use at least 6 characters.",
    error_enter_email_for_reset: "Please enter your email address to reset your password.",
    error_save_settings_failed: "Failed to save settings. Please try again.",
    error_profile_pic_upload_failed: "Failed to upload profile picture. Please try again.",
    error_password_reset_failed: "Failed to send password reset email.",
    error_guest_action_not_allowed: "Guest users cannot perform this action.",
    error_profile_load_failed: "Could not load your profile. Check your connection or try again later.",
    my_subjects: "My Subjects",
    calendar: "Calendar",
    extra_tools: "Extra Tools",
    settings: "Settings",
    app_info: "App Info",
    faq: "FAQ",
    logout_button: "Log Out",
    select_subjects: "Select your subjects",
    settings_title: "Settings",
    profile_section: "Profile",
    save_profile_info_button: "Save Profile",
    success_settings_saved: "Settings saved successfully!",
    choose_theme: "Choose your theme",
    language_preference: "Language Preference",
    dutch: "Dutch",
    english: "English",
    password_reset_section_title: "Reset Password",
    password_reset_section_description: "Click the button to receive a password reset email at {email}.",
    send_reset_email_button: "Send Reset Email",
    settings_account_section: "Account",
    settings_appearance_section: "Appearance",
    settings_help_info_section: "Help & Info",
    settings_privacy_section: "Privacy",
    privacy_policy_content: "Your privacy is important to us. This application collects minimal personal data to provide its functionality. Files you upload are stored in your private storage and are only accessible by you, unless you explicitly share them.",
    version: "Version",
    copyright: "All rights reserved.",
    saving: "Saving...",
    confirm_remove_subjects_warning: "Are you sure you want to deselect these subjects? The associated data (files, notes, etc.) will not be deleted, but will only be visible again once you re-select the subjects.",
    app_offline_message: "You are offline. Changes will sync when you're back online.",
    app_back_online_message: "Welcome back online! Your data will now be synced.",
    confirm_button: "Confirm",
    cancel_button: "Cancel",
    close_button: "Close",
    Selecteer_Niveau: "Select Level",
  }
};

export const guestUser: AppUser = {
  uid: 'guest-user',
  email: 'gast@schoolmaps.app',
  userName: 'Test Gebruiker',
  profilePictureUrl: `https://ui-avatars.com/api/?name=Test&background=random&color=fff`,
  createdAt: Timestamp.now(),
  selectedSubjects: ["nederlands", "wiskunde", "engels", "geschiedenis", "aardrijkskunde"],
  schoolName: 'Test School',
  className: 'Testklas',
  educationLevel: 'havo',
  languagePreference: 'nl',
  themePreference: 'emerald',
};
